
package com.williamfq.domain.model

import java.time.Instant

data class User(
    val id: String,
    val username: String,
    val avatarUrl: String,
    val profilePictureUrl: String? = null,
    val name: String = "Unknown",
    val lastMessage: String? = null,
    val lastActiveTime: Instant? = null,
    val isOnline: Boolean = false,
    val isMuted: Boolean = false,
    val isBlocked: Boolean = false,
    val isDeleted: Boolean = false,
    val isVerified: Boolean = false,
    val isFollowed: Boolean = false,
    val isFollowing: Boolean = false,
    val isBlocking: Boolean = false,
    val isUnblocking: Boolean = false,
    val isUnfollowing: Boolean = false,
    val isUnfollowingMe: Boolean = false,
    val isUnblockingMe: Boolean = false,
    val isBlockingMe: Boolean = false,
    val isFollowingYou: Boolean = false,
    val isBlockingYou: Boolean = false,
    val isUnblockingYou: Boolean = false,
    val isUnfollowingYou: Boolean = false,
    val isFollowingThem: Boolean = false,
    val isBlockingThem: Boolean = false,
    val isUnblockingThem: Boolean = false,
    val isUnfollowingThem: Boolean = false,
    val isFollowingMe: Boolean = false,
    val isBlockingMeThem: Boolean = false,
    val isUnblockingMeThem: Boolean = false,
    val isUnfollowingMeThem: Boolean = false,
    val isBlockingThemMe: Boolean = false,
    val isUnblockingThemMe: Boolean = false,
    val isUnfollowingThemMe: Boolean = false,
    val isBlockingMeYou: Boolean = false,
    val isUnblockingMeYou: Boolean = false,
    val isUnfollowingMeYou: Boolean = false,
    val isBlockingMeThemYou: Boolean = false,
    val isUnblockingMeThemYou: Boolean = false,
    val isUnfollowingMeThemYou: Boolean = false,
    val isBlockingYouMe: Boolean = false,
    val isUnblockingYouMe: Boolean = false,
    val isUnfollowingYouMe: Boolean = false,
    val isBlockingYouThem: Boolean = false,
    val isUnblockingYouThem: Boolean = false,
    val isUnfollowingYouThem: Boolean = false,
    val isBlockingThemYou: Boolean = false,
    val isUnblockingThemYou: Boolean = false,
    val isUnfollowingThemYou: Boolean = false,
    val isBlockingThemMeYou: Boolean = false,
    val isUnblockingThemMeYou: Boolean = false,
    val isUnfollowingThemMeYou: Boolean = false,




)
